### ISSUE TITLE
Makefile for WIN compilation - jump to case error

### ISSUE THREAD

**Issue by rwbc** [differentprogramming/jacksprat#2]
Could you please add a working makefile for compiling it on Windows?
I have tried compiling it and tried a few flags, but one error always prevents the compilation.

the compiler doesn't like that goto jump(s) to register_move
```
jacksprat.cpp:8958:4: error: jump to label 'register_move'
 8958 |    register_move:
```

Note that your 1.0 compilation does not work on older hardware, unlike 0.9 at least.
In my case the hardware does not support popcount, but SSE4.1.
It also does not run on someone elses hardware with popcount, but with SSSE3 only.
I was asked to compile it for him, but failed due to the error above.

**Comment by differentprogramming** [comment]
It's only one file, so a make file seems like overkill, but I admit it doesn't build on default settings.

g++ -o jacksprat.exe  jacksprat.cpp -std=c++11 -fpermissive 
^ that seems to work.  I probably upped the build version to be at least Sandy Bridge or something, but it should build for generic that way.

for Microsoft "cl jacksprat.cpp" is enough

**Comment by rwbc** [comment]
Well, I mentioned 'makefile' only to see if it needs some exotic linker flags, as it seems you are building on linux.
Of course I tried already '-fpermissive', but that did not help, so your proposal did not work either.

I am using mysy2 with gcc/g++, but the 'jump to label' error appears always and a research suggests it should
be fixed codewise.

```
$ g++ -o jacksprat.exe jacksprat.cpp -std=c++11 -fpermissive
jacksprat.cpp:50: warning: "__min" redefined
   50 | #define __min(x,y) ((x)<(y)?(x):(y))
      |
In file included from C:/msys64/mingw64/include/c++/10.2.0/cstdlib:75,
                 from C:/msys64/mingw64/include/c++/10.2.0/stdlib.h:36,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/assert.h:17,
                 from jacksprat.cpp:4:
C:/msys64/mingw64/x86_64-w64-mingw32/include/stdlib.h:125: note: this is the location of the previous definition
  125 | #define __min(a,b) (((a) < (b)) ? (a) : (b))
      |
jacksprat.cpp:51: warning: "__max" redefined
   51 | #define __max(x,y) ((x)>=(y)?(x):(y))
      |
In file included from C:/msys64/mingw64/include/c++/10.2.0/cstdlib:75,
                 from C:/msys64/mingw64/include/c++/10.2.0/stdlib.h:36,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/assert.h:17,
                 from jacksprat.cpp:4:
C:/msys64/mingw64/x86_64-w64-mingw32/include/stdlib.h:124: note: this is the location of the previous definition
  124 | #define __max(a,b) (((a) > (b)) ? (a) : (b))
      |
jacksprat.cpp: In function 'void calc_pawns(bool)':
jacksprat.cpp:3374:52: warning: comparison between 'enum PieceSlotType' and 'enum PieceType' [-Wenum-compare]
 3374 |      if ((x==0 && y==0) || Board[king_pos + x + y] == EMPTY) {
      |                            ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
jacksprat.cpp: In function 'int NegaScout(bool, bool, int, int, int, bool, bool, int, const RelativeMove&, bool, int, int, int)':
jacksprat.cpp:8958:4: error: jump to label 'register_move'
 8958 |    register_move:
      |    ^~~~~~~~~~~~~
jacksprat.cpp:8530:11: note:   from here
 8530 |      goto register_move;
      |           ^~~~~~~~~~~~~
jacksprat.cpp:8573:10: note:   crosses initialization of 'bool repeat'
 8573 |     bool repeat = !somewhere_in_null && RepeatList.count(my_color) >= 3;
      |          ^~~~~~
jacksprat.cpp: In function 'PieceSlotType next_fen_piece(char)':
jacksprat.cpp:10035:1: warning: control reaches end of non-void function [-Wreturn-type]
10035 | }
      | ^

```

**Comment by differentprogramming** [comment]
Nope, I was using msys when I tried g++.
It gave me some warnings, but it worked.

C:\local\jack>g++ -o test.exe jacksprat.cpp -std=c++11 -fpermissive
jacksprat.cpp:50:0: warning: "__min" redefined
 #define __min(x,y) ((x)<(y)?(x):(y))
 ^
In file included from
C:/TDM-GCC-64/x86_64-w64-mingw32/include/assert.h:17:0,
                 from jacksprat.cpp:4:
C:/TDM-GCC-64/x86_64-w64-mingw32/include/stdlib.h:113:0: note: this is the
location of the previous definition
 #define __min(a,b) (((a) < (b)) ? (a) : (b))
 ^
jacksprat.cpp:51:0: warning: "__max" redefined
 #define __max(x,y) ((x)>=(y)?(x):(y))
 ^
In file included from
C:/TDM-GCC-64/x86_64-w64-mingw32/include/assert.h:17:0,
                 from jacksprat.cpp:4:
C:/TDM-GCC-64/x86_64-w64-mingw32/include/stdlib.h:112:0: note: this is the
location of the previous definition
 #define __max(a,b) (((a) > (b)) ? (a) : (b))
 ^
jacksprat.cpp: In function 'void calc_pawns(bool)':
jacksprat.cpp:3374:55: warning: comparison between 'enum PieceSlotType' and
'enum PieceType' [-Wenum-compare]
      if ((x==0 && y==0) || Board[king_pos + x + y] == EMPTY) {
                                                       ^
jacksprat.cpp: In function 'int NegaScout(bool, bool, int, int, int, bool,
bool, int, const RelativeMove&, bool, int, int, int)':
jacksprat.cpp:8958:4: warning: jump to label 'register_move' [-fpermissive]
    register_move:
    ^
jacksprat.cpp:8530:11: note:   from here
      goto register_move;
           ^
jacksprat.cpp:8573:10: note:   crosses initialization of 'bool repeat'
     bool repeat = !somewhere_in_null && RepeatList.count(my_color) >= 3;
          ^

C:\local\jack>dir
 Volume in drive C has no label.
 Volume Serial Number is 2C07-9568

 Directory of C:\local\jack

01/06/2021  07:09 AM    <DIR>          .
01/06/2021  07:09 AM    <DIR>          ..
01/05/2021  05:50 AM         3,097,463 a.exe
01/05/2021  05:43 AM           375,591 jacksprat.cpp
01/05/2021  05:48 AM           592,896 jacksprat.exe
01/05/2021  05:48 AM           815,250 jacksprat.obj
01/06/2021  07:09 AM         3,097,463 test.exe
               5 File(s)      7,978,663 bytes
               2 Dir(s)  133,626,617,856 bytes free


C:\local\jack>g++ --version
g++ (tdm64-1) 5.1.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by differentprogramming** [comment]
By the way, I was using visual studio, which is why those warnings weren't
fixed, because Visual C++ doesn't even throw warnings on my code.

**Comment by rwbc** [comment]
I am sorry, this doesn't help me much.
Your TDM-GCC version is quite old and only with '-fpermissive' it gets compiled. It just gets by with a warning instead.
Probably my quite new version of MinGW doesn't allow it anymore.

A pity, I have compiled hundreds of chess programs during the last couple of years.
Anyhow good luck with Jacksprat.

This the stance in stackoverflow:


> The -fpermissive flag causes the compiler to report some things that are actually errors (but are permitted by some compilers) as warnings, to permit code to compile even if it doesn't conform to the language rules. You really should fix the underlying problem.
> 

https://stackoverflow.com/questions/8843818/what-does-the-fpermissive-flag-do

Best regards,
Guenther (maintainer of the XB/UCI chronology and RWBC)
https://rwbc-chess.de/

> 
> Nope, I was using msys when I tried g++. It gave me some warnings, but it worked.

```
C:\local\jack>g++ -o test.exe jacksprat.cpp -std=c++11 -fpermissive
jacksprat.cpp:50:0: warning: "__min" redefined
 #define __min(x,y) ((x)<(y)?(x):(y))
 ^
In file included from
C:/TDM-GCC-64/x86_64-w64-mingw32/include/assert.h:17:0,
                 from jacksprat.cpp:4:
C:/TDM-GCC-64/x86_64-w64-mingw32/include/stdlib.h:113:0: note: this is the
location of the previous definition
 #define __min(a,b) (((a) < (b)) ? (a) : (b))
 ^
jacksprat.cpp:51:0: warning: "__max" redefined
 #define __max(x,y) ((x)>=(y)?(x):(y))
 ^
In file included from
C:/TDM-GCC-64/x86_64-w64-mingw32/include/assert.h:17:0,
                 from jacksprat.cpp:4:
C:/TDM-GCC-64/x86_64-w64-mingw32/include/stdlib.h:112:0: note: this is the
location of the previous definition
 #define __max(a,b) (((a) > (b)) ? (a) : (b))
 ^
jacksprat.cpp: In function 'void calc_pawns(bool)':
jacksprat.cpp:3374:55: warning: comparison between 'enum PieceSlotType' and
'enum PieceType' [-Wenum-compare]
      if ((x==0 && y==0) || Board[king_pos + x + y] == EMPTY) {
                                                       ^
jacksprat.cpp: In function 'int NegaScout(bool, bool, int, int, int, bool,
bool, int, const RelativeMove&, bool, int, int, int)':
jacksprat.cpp:8958:4: warning: jump to label 'register_move' [-fpermissive]
    register_move:
    ^
jacksprat.cpp:8530:11: note:   from here
      goto register_move;
           ^
jacksprat.cpp:8573:10: note:   crosses initialization of 'bool repeat'
     bool repeat = !somewhere_in_null && RepeatList.count(my_color) >= 3;
          ^

C:\local\jack>dir
 Volume in drive C has no label.
 Volume Serial Number is 2C07-9568

 Directory of C:\local\jack

01/06/2021  07:09 AM    <DIR>          .
01/06/2021  07:09 AM    <DIR>          ..
01/05/2021  05:50 AM         3,097,463 a.exe
01/05/2021  05:43 AM           375,591 jacksprat.cpp
01/05/2021  05:48 AM           592,896 jacksprat.exe
01/05/2021  05:48 AM           815,250 jacksprat.obj
01/06/2021  07:09 AM         3,097,463 test.exe
               5 File(s)      7,978,663 bytes
               2 Dir(s)  133,626,617,856 bytes free


C:\local\jack>g++ --version
g++ (tdm64-1) 5.1.0
Copyright (C) 2015 Free Software Foundation, Inc.
```

**Comment by differentprogramming** [comment]
Oops, hit send on an empty message.

I'll play with it on a new copy of Linux that has a new version of g++ and
see if I can get rid of the errors.

**Comment by differentprogramming** [comment]
It should be fixed now.

**Comment by rwbc** [comment]
> 
> 
> It should be fixed now.

Thanks a lot Joshua, compiles fine now!
I really appreciate you spent some time on fixing this.

Guenther
